### ISSUE TITLE
若存在单条不支持的广告规则，同一站点内其他规则也不能生效

### ISSUE THREAD

**Issue by MkQtS** [LakorTi/Via#1349]
假定这样一个网页的链接为`https://example.com/example.html`

```html
<html>
<head>
	<title>Example page</title>
</head>

<body>
	<div class='toHide'>
		<h2>Hide area</h2>
		<p><i>This area should be hide.</i></p>
	</div>
	<div class='toBeRed' style="background-color: #0f0">
		<h2>Green area</h2>
		<p><i>This area should be Red.</i></p>
	</div>
</body>
</html>
```

添加这样两条广告规则：

```adblock
example.com##.toHide
example.com##.toBeRed:style(background-color: #f00 !important)
```

因第二条规则Via不支持，第一条也会失效；若删去第二条，则第一条能够生效。

希望不要株连无辜。。。

**Comment by tuyafeng** [comment]
根据 [CSS 选择器参考手册](https://www.w3school.com.cn/cssref/css_selectors.asp)，`.toBeRed:style(background-color: #f00 !important)` 看起来不是一个合法的 css 选择器。请问 `example.com##.toBeRed:style(background-color: #f00 !important)
` 是 Adguard 过滤器写法吗？

**Comment by tuyafeng** [comment]
另外，为了运行性能，一个网站对应的元素过滤器在应用时，会合并为一条规则，这意味着，如果当中有一条错误规则，则该网站对应的所有过滤器规则都不会生效。考虑到编写自定义规则的都是小部分人，所以有这么个设定。

**Comment by tuyafeng** [comment]
是的，后续会过滤掉这样不支持的规则，也非常感谢你的反馈。
