### ISSUE TITLE
Open link in new Tab

### ISSUE THREAD

**Issue by mirbuf** [LakorTi/Via#20]
Previous version had a setting to open links in a new Tab.
Version 3.0 seems to be missing this option. Can it be added again, please?

**Comment by LakorTi** [comment]
It just in the menu, you can choose it.

**Comment by mirbuf** [comment]
I swear it is not in menu. In version 2.2.5 it was under Settings -> Advanced, together with:
Way of opening in News (Background), Open Link in (New Tab), Text Encoding (UTF-8), Enable Javascript, Enable Cookies, Allow Website Intent.
In 3.1.2, under Settings -> Advanced, I see only these:
Enable Javascript, Reopen Tabs on start, Go Back without Reload
