### ISSUE TITLE
Auto Back before page

### ISSUE THREAD

**Issue by kae-sakura** [LakorTi/Via#222]
now browsing site, suddenly return to the previous page

please fix

**Comment by LakorTi** [comment]
I am confused about this issue. I want to fixed it but i can not get any clue. Can u give me the link of website when it had happend?

**Comment by kae-sakura** [comment]
sorry.
I can not confirm the always occur pageback site....

**Comment by LakorTi** [comment]
Thanks for your feedback. I had fixed this issue in the latest version(v3.4.0), you can update to solve this.
