### ISSUE TITLE
Japanese Play Store Description is old

### ISSUE THREAD

**Issue by kae-sakura** [LakorTi/Via#223]
I write new description

If use it, I'm happy

100万ダウンロード突破！軽量、高速ブラウザの決定版！

✔広告なし
Viaブラウザには設定画面含め、邪魔な広告はありません。

✔無料
全ての機能が無料にてご利用できます。

✔不要な通知なし
天気や別のアプリなどのポップアップ通知はありません。

✔日本語対応
日本人による翻訳が行われています。

✔軽量、高速
アプリサイズも小さく端末の容量を圧迫しません。
動作中のメモリ使用も多くありません。

■機能
• UIのカスタマイズ
• 広告ブロック機能
• 個人情報保護
• ブックマーク
• ナイトモード
• PCビュー機能
• 翻訳
• ページ内検索
• 複数の検索エンジン対応
• ウェブページの保存（mht形式）
• 画像のみの表示機能
• ホームページを自由にカスタマイズ
• フルスクリーン表示
• User Agentの変更

その他にも多くの機能が搭載されています。

■権限に関して
• 位置情報
ウェブサイトに位置情報を提供するために使用しています。

• ストレージ
画像やメディアなどのダウンロードを行うために使用しています。

■日本語翻訳について
有志による翻訳を行っています。
新しいバージョンがリリース後、実際の表示箇所を確認しつつ翻訳しています。
タイミングにより翻訳がされていない所がある可能性があります。ご了承ください。

また、翻訳が変な箇所などありましたら、コメントにてご報告お願い致します。
該当箇所を確認し、必要であれば修正を行います。

**Comment by LakorTi** [comment]
Well done! Thanks for your work! :D

**Comment by kae-sakura** [comment]
Thanks you!
