### ISSUE TITLE
是否可以提供应用内嵌版本

### ISSUE THREAD

**Issue by weihai4099** [LakorTi/Via#242]
最近在搞安卓。需要用到webview。想问一下是否可以提供内嵌版本

**Comment by tuyafeng** [comment]
怎么个内嵌，提供个设置好的 webview 以供使用吗？使用的是系统的 webview 组件，自己设置下就可以。

**Comment by weihai4099** [comment]
那怎么设置啊，好像没有提供源码。因为不是专业搞安卓的。

**Comment by tuyafeng** [comment]
自己去看看 webview 的官方文档吧。
