### ISSUE TITLE
[bug?] 关于隐身浏览的问题

### ISSUE THREAD

**Issue by fichtl** [LakorTi/Via#261]
你好，请问隐身浏览的功能是否包括身份的隐藏？
历史记录确实被隐藏了，但是服务器依然可以识别我的身份🤔
暂时还没看源码只是遇到了这个问题所以想问一下
（说不定就是个bug😏）

**Comment by LakorTi** [comment]
因为隐身模式滥用的一些问题（例如即使不需要隐身也长期开着隐身模式），现在的隐身模式默认是启用 Cookie 的，与正常模式的区别在于其不会在本地保留历史记录，同时会强制发送 DO NOT TRACK（无论用户如何设置）。
