### ISSUE TITLE
Can't upload any files.

### ISSUE THREAD

**Issue by GFOXSH** [LakorTi/Via#35]
Hello! I can't upload any file to
http://m.vk.com or http://4pda.ru
I choose a file using Total Commander and VIA Browser freezes... How to fix this problem? Thank you in advance!

**Comment by LakorTi** [comment]
Got it. I will try to fix it.

**Comment by GFOXSH** [comment]
@LakorTi and so, I can't open Youtube to fullscreen size...

**Comment by h599** [comment]
@LakorTI,

I'm one of your Via WebBrowser fan!!
Admin, can i ask a new feature to via please?

The feature i want is "page info" (just like what the "uc mini" browser have), the feature that so useful for us the user. 

Page info feature mean, we can check what url are we going to click, and what page are we at..

It's soo useful :D

It can make us avoid scamming site, fake login, or even malware site.. 

After we hold a link for a long time the "dialog" that via browser have, via have an option of "page info" before the "Mark as AD" option.

ScreenShot, 
https://ibb.co/fAKyfk 
https://ibb.co/iJMN6Q

Please add "page info" feature.. please

Sincerely,

Your Via-WebBrowser Fan!! :D

**Comment by GFOXSH** [comment]
Hello! In one update you tell, that file's upload has been fixed, but why I try to upload file I get same problem (in the newest version too).
