### ISSUE TITLE
V3.90 Crashes on Android 4.4.2

### ISSUE THREAD

**Issue by zo-shin** [LakorTi/Via#357]
The app crashes when **Settings** icon is clicked.
![via](https://user-images.githubusercontent.com/38669548/57018762-32198a80-6c57-11e9-9d28-2a19d9342d75.jpg)

**Comment by FONZACUS** [comment]
thanks, can also confirm 3.90v2 fixed it.

**Comment by zo-shin** [comment]
You are welcome. It’s fixed in V**3.91**.
