### ISSUE TITLE
Feature request: Block third party cookies

### ISSUE THREAD

**Issue by pedalmeat** [LakorTi/Via#382]
Block third party cookies option or share the script below:

var meta=document.createElement("meta"); 
meta.httpEquiv="Content-Security-Policy"; 
meta.content="script-src 'unsafe-inline' *.example.com;"; 
document.getElementsByTagName("meta")[0].appendChild(meta);

**Comment by LakorTi** [comment]
Got it. I will add this feature next version(v3.9.5).
