### ISSUE TITLE
via置于后台不超过5分钟..再切回来前面打开的页面就会空白不见

### ISSUE THREAD

**Issue by lubocheng** [LakorTi/Via#392]
如题..体验很难受

**Comment by LakorTi** [comment]
问题已收到，后续会关注被误杀这块，目前可以考虑先将 via 加到类似内存清理白名单之类的地方。

这里顺带一提，因为安卓保活机制的问题，可以简单说说，即前台进程>后台服务>缓存。也因为这样的缘故，很多国产 app 为了保活都拼命加服务或者通过一些奇技淫巧来驻留后台，via 没做这方面的相关工作，所以在多任务中优先级会靠后，也就是优先被杀 - -。

**Comment by lubocheng** [comment]
@LakorTi 应该不是保活的问题..因为已经加到白名单了
