### ISSUE TITLE
为什么脚本不能使用？

### ISSUE THREAD

**Issue by imjinbo** [LakorTi/Via#393]
不管是用官方推荐的还是我自己写的，都不能生效（在代码中加了alert，并不会弹出），怎么解决呢

**Comment by LakorTi** [comment]
试试这个最基本的用例。

alert('hello');

**Comment by imjinbo** [comment]
> 试试这个最基本的用例。
> 
> 警报（'你好'）;

并不可以，我已经设置了“*”通用页面，但是还是不会弹出。
并且还发现了另一个问题：
在安卓5.0上面，运行网页：‘https://cn.vuejs.org/v2/guide/'，
点击左上角的三条横线，并不会展开，但是在安卓8就可以，请看一下。

**Comment by iyoucheng** [comment]
> > 试试这个最基本的用例。
> > alert('hello');;
> 
> 并不可以，我已经设置了“*”通用页面，但是还是不会弹出。
> 并且还发现了另一个问题：
> 在安卓5.0上面，运行网页：‘[https://cn.vuejs.org/v2/guide/'，](https://cn.vuejs.org/v2/guide/'%EF%BC%8C)
> 点击左上角的三条横线，并不会展开，但是在安卓8就可以，请看一下。

我也是，写的脚本都没有地方调用。

**Comment by imjinbo** [comment]
> > > 试试这个最基本的用例。
> > > alert('hello');;
> > 
> > 
> > 并不可以，我已经设置了“*”通用页面，但是还是不会弹出。
> > 并且还发现了另一个问题：
> > 在安卓5.0上面，运行网页：‘[https://cn.vuejs.org/v2/guide/'，](https://cn.vuejs.org/v2/guide/'%EF%BC%8C)
> > 点击左上角的三条横线，并不会展开，但是在安卓8就可以，请看一下。
> 
> 我也是，写的脚本都没有地方调用。

不清楚是怎么回事...

**Comment by tuyafeng** [comment]
一般来说会正常调用的，我刚刚测试了下，分号是必须的，且最好是一个，避免出现奇怪的错误。

```
alert('hello');
```
