### ISSUE TITLE
网页js无法使用mediaDevices API调用摄像头

### ISSUE THREAD

**Issue by JerryXia** [LakorTi/Via#394]
以下是我写的一个测试demo，在via浏览器调试发现好像是权限阻止了，在有的浏览器中正常，猜测是没有在AndroidManifest.xml中声明 
https://cdn.guqiankun.com/jsqrcode/8.html

**Comment by LakorTi** [comment]
对的，via 没有申请相关摄像头权限，因为之前测试过程中发现部分 html5 的特性即使在存在权限的情况也表现异常，猜测可能是 webview 内核的原因，故为了减少猜疑只申请了最基本的权限。
