### ISSUE TITLE
App is tracking me through yahoo

### ISSUE THREAD

**Issue by SimonGhoul** [LakorTi/Via#397]
Uses flurry, this page and my blockada verifies it https://reports.exodus-privacy.eu.org/en/reports/search/mark.via.gp/ (flurry is from yahoo, so yahoo trackers. Same as tumblr)

I am extremely disappointed by this app, I had high hopes for it.

Edit: I also can't download anything from any site without blocking your trackers. That's the sketchiest thing fam

**Comment by SilverWx** [comment]
The developers should be more transparent about data collection, it's very strange. Thanks for warning

**Comment by ram108** [comment]
Any comments on spying from developers?

**Comment by SimonGhoul** [comment]
The dev is also chinese. China is not trustworthy because the government there is very manipulative and bad. The government is already pretty privacy invasive already within the country. And forces companies to censor things worldwide from their products in order to appeal china

But, the trackers are not from china, just in case. That's something I should say in case someone else thinks that the chinese government is spying on them. Only yahoo is receiving this info as far as I know and this is just to sell this info to ads and stuff. I don't think they take very personal info but it's still too much to require trackers to track your downloads. That's just not ok. But yeah this comment is just to disclaim people that the chinese government is not spying on you, and to scare you a little bit at the beggining because I am a cunt

I should had taken screenshots, but if you install blokada in your phone, get a few filters, and then go to the host log or something like that you can find which trackers are blocked when you open the app (I suggest you are at least a bit savvy and patient to know which ones are false positives and which ones come from the app. I am not a expert, you don't need to be a expert). 
Almost every site and app has trackers, it's not really a big deal unless you want to go through the effort of being anonymous. But it's wrong when the way they are doing it is sketchy or they are taking too much info. I find it pretty sketchy to not be able to download without blocking a tracker from the browser (not from the site) because browsers don't need to track my downloads or have them go through their own server, specially if I don't know about it. I am not sure if they are taking too much info, they probably are, but I am sure it goes to yahoo and _their partners_. Partners can be pretty invasive, I honestly blame facebook partners more than facebook. It's just creepy as fuck.

**Comment by SimonGhoul** [comment]
I honestly don't mind trackers if it's just for advertising. It's still wrong but no harm in that. I just don't like it when it's sketchy or it's tracking literally where I live, just like some of facebook partners do (not facebook, but facebook still connects the dots when they shouldn't)

**Comment by dajcou** [comment]
About a year ago in the Telegram group someone was able to take out Flurry & chinese websites the app connects to and upload their own version of Via to their blogspot blog, by editing/modding the apk of the file. Is that still able to be done? 

Link to the modded version (it's over a year old):
http://capaspt.blogspot.com/2018/07/via-browser-v337-mod.html

**Comment by turnmind** [comment]
> The dev is also chinese. China is not trustworthy because the government there is very manipulative and bad. The government is already pretty privacy invasive already within the country. And forces companies to censor things worldwide from their products in order to appeal china
> 
> But, the trackers are not from china, just in case. That's something I should say in case someone else thinks that the chinese government is spying on them. Only yahoo is receiving this info as far as I know and this is just to sell this info to ads and stuff. I don't think they take very personal info but it's still too much to require trackers to track your downloads. That's just not ok. But yeah this comment is just to disclaim people that the chinese government is not spying on you, and to scare you a little bit at the beggining because I am a cunt
> 
> I should had taken screenshots, but if you install blokada in your phone, get a few filters, and then go to the host log or something like that you can find which trackers are blocked when you open the app (I suggest you are at least a bit savvy and patient to know which ones are false positives and which ones come from the app. I am not a expert, you don't need to be a expert).
> Almost every site and app has trackers, it's not really a big deal unless you want to go through the effort of being anonymous. But it's wrong when the way they are doing it is sketchy or they are taking too much info. I find it pretty sketchy to not be able to download without blocking a tracker from the browser (not from the site) because browsers don't need to track my downloads or have them go through their own server, specially if I don't know about it. I am not sure if they are taking too much info, they probably are, but I am sure it goes to yahoo and _their partners_. Partners can be pretty invasive, I honestly blame facebook partners more than facebook. It's just creepy as fuck.

`Put away your prejudice against China. The Chinese government has not eavesdropped on the privacy of users. I don't know, but the United States will definitely, and all of them are participating in the US Internet companies. The Chinese government cannot tolerate illegal crimes, pornography, and reactionary information on the Internet. For this reason, China will become the safest country in the world. China is a developing country, and many Internet-related laws are still being improved, including the regulation of user privacy. Therefore, there are many individuals and companies that collect user privacy and have little to do with the Chinese government. From Chinese users`

**Comment by dajcou** [comment]
Initializing ...
***Initializing PersonalDNSFilter Version 1.50.32!***
Using Directory: /storage/emulated/0/PersonalDNSFilter/
Using Blocking Mode!
VPN Connected!
DNS Filter: Next filter reload:Wed Nov 06 19:23:49 EST 2019
VPN Runner Thread 1 started!
[opened Via Browser]
X 	cfg.flurry.com
X 	cfg.flurry.com
X 	data.flurry.com
X 	data.flurry.com
[went to Google]
✓	www.google.com
✓	www.google.com
X 	mobile-collector.newrelic.com
X 	mobile-collector.newrelic.com
✓	android.clients.google.com
✓	android.clients.google.com
X 	cfg.flurry.com
X 	cfg.flurry.com
X 	j.pro.sip.igate.nocell.io
X 	j.pro.sip.igate.nocell.io
X 	data.flurry.com
X 	data.flurry.com
[typed in search phrase on Via]
X 	data.flurry.com
X 	data.flurry.com
✓	www.google.com
✓	safebrowsing.googleapis.com
✓	www.google.com
✓	safebrowsing.googleapis.com
✓	encrypted-tbn0.gstatic.com
✓	encrypted-tbn1.gstatic.com
✓	encrypted-tbn1.gstatic.com
✓	encrypted-tbn0.gstatic.com
✓	lh3.googleusercontent.com
✓	lh3.googleusercontent.com
X 	data.flurry.com
X 	data.flurry.com
[went to Reddit.com]
✓	www.reddit.com
✓	www.reddit.com
X 	events.redditmedia.com
X 	events.redditmedia.com
✓	app.link
✓	app.link
X 	api2.branch.io
X 	api2.branch.io
✓	www.redditmedia.com
✓	www.redditmedia.com
✓	a.thumbs.redditmedia.com
✓	b.thumbs.redditmedia.com
✓	a.thumbs.redditmedia.com
✓	b.thumbs.redditmedia.com
✓	styles.redditmedia.com
✓	www.redditstatic.com
✓	styles.redditmedia.com
✓	www.redditstatic.com
X 	data.flurry.com
X 	data.flurry.com

 data.flurry.com & cfg.flurry.com seem to be trying to access all urls and searches I go to through Via :/

**Comment by SimonGhoul** [comment]
> > The dev is also chinese. China is not trustworthy because the government there is very manipulative and bad. The government is already pretty privacy invasive already within the country. And forces companies to censor things worldwide from their products in order to appeal china
> > But, the trackers are not from china, just in case. That's something I should say in case someone else thinks that the chinese government is spying on them. Only yahoo is receiving this info as far as I know and this is just to sell this info to ads and stuff. I don't think they take very personal info but it's still too much to require trackers to track your downloads. That's just not ok. But yeah this comment is just to disclaim people that the chinese government is not spying on you, and to scare you a little bit at the beggining because I am a cunt
> > I should had taken screenshots, but if you install blokada in your phone, get a few filters, and then go to the host log or something like that you can find which trackers are blocked when you open the app (I suggest you are at least a bit savvy and patient to know which ones are false positives and which ones come from the app. I am not a expert, you don't need to be a expert).
> > Almost every site and app has trackers, it's not really a big deal unless you want to go through the effort of being anonymous. But it's wrong when the way they are doing it is sketchy or they are taking too much info. I find it pretty sketchy to not be able to download without blocking a tracker from the browser (not from the site) because browsers don't need to track my downloads or have them go through their own server, specially if I don't know about it. I am not sure if they are taking too much info, they probably are, but I am sure it goes to yahoo and _their partners_. Partners can be pretty invasive, I honestly blame facebook partners more than facebook. It's just creepy as fuck.
> 
> `Put away your prejudice against China. The Chinese government has not eavesdropped on the privacy of users. I don't know, but the United States will definitely, and all of them are participating in the US Internet companies. The Chinese government cannot tolerate illegal crimes, pornography, and reactionary information on the Internet. For this reason, China will become the safest country in the world. China is a developing country, and many Internet-related laws are still being improved, including the regulation of user privacy. Therefore, there are many individuals and companies that collect user privacy and have little to do with the Chinese government. From Chinese users`

You would be more believable if you didn't sound brainwashed or as if you just copy and pasted it from somewhere. You even have it highlighted. You ignore a lot of things I said, and also try to paint me in a back light (A white racist american against china that thinks china is the only government tracking me. I am not even american). I am not even going to bother arguing with you. 
You are brainwashed. _get out of here_
If you want to bring tens of thousands of chinese brainwashed people that are just scared of their own government like they did to a videogame dev, go ahead. (I am not saying every chinese person is bad or brainwashed. I know there are many that are fine)

**Comment by SimonGhoul** [comment]
> IInitializing ...
> _**Initializing PersonalDNSFilter Version 1.50.32!**_
> Using Directory: /storage/emulated/0/PersonalDNSFilter/
> Using Blocking Mode!
> VPN Connected!
> DNS Filter: Next filter reload:Wed Nov 06 19:23:49 EST 2019
> VPN Runner Thread 1 started!
> [opened Via Browser]
> X cfg.flurry.com
> X cfg.flurry.com
> X data.flurry.com
> X data.flurry.com
> [went to Google]
> ✓ [www.google.com](http://www.google.com)
> ✓ [www.google.com](http://www.google.com)
> X mobile-collector.newrelic.com
> X mobile-collector.newrelic.com
> ✓ android.clients.google.com
> ✓ android.clients.google.com
> X cfg.flurry.com
> X cfg.flurry.com
> X j.pro.sip.igate.nocell.io
> X j.pro.sip.igate.nocell.io
> X data.flurry.com
> X data.flurry.com
> [typed in search phrase on Via]
> X data.flurry.com
> X data.flurry.com
> ✓ [www.google.com](http://www.google.com)
> ✓ safebrowsing.googleapis.com
> ✓ [www.google.com](http://www.google.com)
> ✓ safebrowsing.googleapis.com
> ✓ encrypted-tbn0.gstatic.com
> ✓ encrypted-tbn1.gstatic.com
> ✓ encrypted-tbn1.gstatic.com
> ✓ encrypted-tbn0.gstatic.com
> ✓ lh3.googleusercontent.com
> ✓ lh3.googleusercontent.com
> X data.flurry.com
> X data.flurry.com
> [went to Reddit.com]
> ✓ [www.reddit.com](http://www.reddit.com)
> ✓ [www.reddit.com](http://www.reddit.com)
> X events.redditmedia.com
> X events.redditmedia.com
> ✓ app.link
> ✓ app.link
> X api2.branch.io
> X api2.branch.io
> ✓ [www.redditmedia.com](http://www.redditmedia.com)
> ✓ [www.redditmedia.com](http://www.redditmedia.com)
> ✓ a.thumbs.redditmedia.com
> ✓ b.thumbs.redditmedia.com
> ✓ a.thumbs.redditmedia.com
> ✓ b.thumbs.redditmedia.com
> ✓ styles.redditmedia.com
> ✓ [www.redditstatic.com](http://www.redditstatic.com)
> ✓ styles.redditmedia.com
> ✓ [www.redditstatic.com](http://www.redditstatic.com)
> X data.flurry.com
> X data.flurry.com
> 
> data.flurry.com & cfg.flurry.com seem to be trying to access all urls and searches I go to through Via :/
> 
> What data is given to Flurry?

Damn that is really invasive. You should had tried downloading something just to confirm. You can find more about flurry here https://www.flurry.com/analytics.html I guess, owned by verizon(yahoo). It's just like google adsense I am guessing but that can be abused to get your location and other info and give companies too much info for advertising. I personally like to block all trackers but not the ads with ublock (desktop browser extension).

It seems pretty friendly sure. Every developer likes to get information on their apps and know if there are any issues. I don't know exactly how good devs use analytics, but what set me off from this dev is that you don't have the option to block them and you also can't download anything if the app is not tracking your downloads (it tracks your downloads. Why do you need to track downloads or track so much about downloads that you make your tracker be required to download?). I don't think there's any telling into what the app is tracking. It's tracking your usage maybe and maybe some things you type and what it finds on the page (I know it won't steal your password, unless it's on a site that's not encrypted, an http site..... I don't think it would be legal if verizon purposelly made it so people can bypass encryption and read what you type. But most paranoid privacy people think everything reads what you are typing)

**Comment by SimonGhoul** [comment]
> About a year ago in the Telegram group someone was able to take out Flurry & chinese websites the app connects to and upload their own version of Via to their blogspot blog, by editing/modding the apk of the file. Is that still able to be done?
> 
> Link to the modded version (it's over a year old):
> http://capaspt.blogspot.com/2018/07/via-browser-v337-mod.html
> 
> edit: After downloading DNSFilter it still shows data.flurry.com as trying to connect even with that modded app above. Apparently it didn't really edit it out. How does one get rid of flurry? Jeez.

Are you sure flurry is chinese? My research says it's Verizon, which owns Yahoo. And the page says it's owned by Yahoo.

**Comment by dajcou** [comment]
> > About a year ago in the Telegram group someone was able to take out Flurry & chinese websites the app connects to and upload their own version of Via to their blogspot blog, by editing/modding the apk of the file. Is that still able to be done?
> > Link to the modded version (it's over a year old):
> > http://capaspt.blogspot.com/2018/07/via-browser-v337-mod.html
> > edit: After downloading DNSFilter it still shows data.flurry.com as trying to connect even with that modded app above. Apparently it didn't really edit it out. How does one get rid of flurry? Jeez.
> 
> Are you sure flurry it's chinese? My research says it's Verizon, which owns Yahoo. And the page says it's owned by Yahoo.

No, on the download page of the modded version it says "Chinese hosts removed". Apparently there is other things besides flurry that may be up to no good.

**Comment by SimonGhoul** [comment]
> > > About a year ago in the Telegram group someone was able to take out Flurry & chinese websites the app connects to and upload their own version of Via to their blogspot blog, by editing/modding the apk of the file. Is that still able to be done?
> > > Link to the modded version (it's over a year old):
> > > http://capaspt.blogspot.com/2018/07/via-browser-v337-mod.html
> > > edit: After downloading DNSFilter it still shows data.flurry.com as trying to connect even with that modded app above. Apparently it didn't really edit it out. How does one get rid of flurry? Jeez.
> > 
> > 
> > Are you sure flurry it's chinese? My research says it's Verizon, which owns Yahoo. And the page says it's owned by Yahoo.
> 
> No, on the download page of the modded version it says "Chinese hosts removed". Apparently there is other things besides flurry that may be up to no good.

damn

**Comment by LakorTi** [comment]
There is a misunderstanding. Via do **NOT** use flurry to send your browsing history or any privacy thing. I just use it to record basic frequency of some functions, for example, the "Night Mode" click times per day, and something like this. What I can get in flurry dashboard, just some numbers in via usage.

**Comment by turnmind** [comment]
> > > The dev is also chinese. China is not trustworthy because the government there is very manipulative and bad. The government is already pretty privacy invasive already within the country. And forces companies to censor things worldwide from their products in order to appeal china
> > > But, the trackers are not from china, just in case. That's something I should say in case someone else thinks that the chinese government is spying on them. Only yahoo is receiving this info as far as I know and this is just to sell this info to ads and stuff. I don't think they take very personal info but it's still too much to require trackers to track your downloads. That's just not ok. But yeah this comment is just to disclaim people that the chinese government is not spying on you, and to scare you a little bit at the beggining because I am a cunt
> > > I should had taken screenshots, but if you install blokada in your phone, get a few filters, and then go to the host log or something like that you can find which trackers are blocked when you open the app (I suggest you are at least a bit savvy and patient to know which ones are false positives and which ones come from the app. I am not a expert, you don't need to be a expert).
> > > Almost every site and app has trackers, it's not really a big deal unless you want to go through the effort of being anonymous. But it's wrong when the way they are doing it is sketchy or they are taking too much info. I find it pretty sketchy to not be able to download without blocking a tracker from the browser (not from the site) because browsers don't need to track my downloads or have them go through their own server, specially if I don't know about it. I am not sure if they are taking too much info, they probably are, but I am sure it goes to yahoo and _their partners_. Partners can be pretty invasive, I honestly blame facebook partners more than facebook. It's just creepy as fuck.
> > 
> > 
> > `Put away your prejudice against China. The Chinese government has not eavesdropped on the privacy of users. I don't know, but the United States will definitely, and all of them are participating in the US Internet companies. The Chinese government cannot tolerate illegal crimes, pornography, and reactionary information on the Internet. For this reason, China will become the safest country in the world. China is a developing country, and many Internet-related laws are still being improved, including the regulation of user privacy. Therefore, there are many individuals and companies that collect user privacy and have little to do with the Chinese government. From Chinese users`
> 
> You would be more believable if you didn't sound brainwashed or as if you just copy and pasted it from somewhere. You even have it highlighted. You ignore a lot of things I said, and also try to paint me in a back light (A white racist american against china that thinks china is the only government tracking me. I am not even american). I am not even going to bother arguing with you.
> You are brainwashed. _get out of here_
> If you want to bring tens of thousands of chinese brainwashed people that are just scared of their own government like they did to a videogame dev, go ahead. (I am not saying every chinese person is bad or brainwashed. I know there are many that are fine)
> 
> Edit: I even said that china is not tracking you. Tell me you are not brainwashed. I said Yahoo/Verizon is tracking you, and that people should not be afraid of the chinese government in this case just because the dev was chinese since the trackers _are not chinese._ The dev is not even working with china. Seriously things like you disgust me, you are not even people, you are a bot. If you don't like me treating you like shit then you shouldn't call me a big piece of shit.
> Again, if you reply I won't reply back. You disgust me. Even if you were actually human, you still are one of those that are too quick to call someone a piece of shit and assume things about them, and you are the main problem of our current society

Come to China more often, Don't hide at home to read the newspaper and accuse us. you are brainwashed by the Western media. We are more awake than anyone else. Your so-called democratic freedom is simply a joke, ok? Caucasian is the most arrogant and prejudiced guy in the world, poor you guys. In a few years, see who’s country is really strong.
