### ISSUE TITLE
YouTube播放画面拉伸

### ISSUE THREAD

**Issue by LongchuanYu** [LakorTi/Via#400]
机型：huawei mate30pro
EMUI版本：10.0.0
Android版本：10

**描述：**
用via播放youtube视频会发生画面拉伸的情况

**备考**
1.用华为自带浏览器同样发生
2.via电脑模式同样发生
3.试了一下夸克浏览器->正常

**Comment by RtYkk** [comment]
Android 10 on OG pixel 无法复现，有点好奇是什么情况。能不能上个截图

**Comment by LongchuanYu** [comment]
> Android 10 on OG pixel 无法复现，有点好奇是什么情况。能不能上个截图

重新安装了一下via，已经不发生这个情况了，非常感谢回复。
