### ISSUE TITLE
3.9.3版本书签页无法对书签进行自定义排序

### ISSUE THREAD

**Issue by LSL1618** [LakorTi/Via#405]
3.9.3版本书签页无法对书签进行自定义排序，最好能支持批量编辑模式下拖动排序。顺便二维码扫描插件或组件能默认集成或安装就好了。

**Comment by LakorTi** [comment]
更新到最新版本试试，目前的最新版是 v3.9.4，这块没怎么调整过，应该是一直可以拖拽排序的。
