### ISSUE TITLE
Feature Request: Optionally Deleting Browsing Data on Exit

### ISSUE THREAD

**Issue by gspolly** [LakorTi/Via#42]
Hi there,

I love this browser, I totally appreciate your great work. Keep it up!
I would like to see an option to delete all browsing data on exit or a description of the add-on API (if existent / powerful enough) so that it could be coded by the community.

Cheers, Polly

**Comment by LakorTi** [comment]
Hey my friend,

I am sorry to tell you an option to delete all browsing data is not in my plan. But next big version(4.0+), I will publish a add-on API document and show you all about that.
