### ISSUE TITLE
内存优化

### ISSUE THREAD

**Issue by LivedForward** [LakorTi/Via#423]
感觉是不是应该优化一下内存了。
![Screenshot_2020-01-10-12-38-48-771_com android settings](https://user-images.githubusercontent.com/19593304/72126357-bc99b880-33a6-11ea-90a3-218c91039c09.png)

**Comment by LakorTi** [comment]
在 3.9.8 及之后的版本中已经优化了网页相关的内存占用，大幅缩小了程序缓存的网页数目，可以更新看看，我这边测试长时间浏览内存已经得到了很好的控制（具体缓存大小根据 webview 版本不同有不同，一般不会超过 500M），如果还存在问题，欢迎及时反馈。
