### ISSUE TITLE
电脑模式的ua版本未能否正常匹配

### ISSUE THREAD

**Issue by Lengsir** [LakorTi/Via#425]
手机模式的ua版本为正常的webview版本78（Mozilla/5.0 (Linux; Android 10; PCT-AL10 Build/HUAWEIPCT-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36），
但是切换到电脑模式后却变成了47版（Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36），
能否做成自动匹配版本的？

**Comment by LakorTi** [comment]
3.9.8 版本之后，内置电脑模式的 UA 已经更新了，出于安卓碎片化的原因，暂时不考虑从内建 UA 中提取做电脑模式的 UA。
