### ISSUE TITLE
有办法开启支持手机更好显示的“简化版视图”功能吗？

### ISSUE THREAD

**Issue by kingo132** [LakorTi/Via#428]
chrome和brave手机版浏览器都支持这个功能，via浏览器好像没看到，不知道是不是有办法开启？

**Comment by LakorTi** [comment]
简单查阅了下，得知是类似「阅读模式」的功能（如有误解请指出）。Via 还没有类似这样「阅读模式」的想法，因为之前尝试实现过但效果并不理想，在有更好的做法之前暂时不会考虑。
