### ISSUE TITLE
Help with Custom CSS

### ISSUE THREAD

**Issue by cybarspace** [LakorTi/Via#429]
Please consider adding a guide/documentation to the Readme file about how exactly to customize the Homepage through the "Add Custom CSS" option.

I know very basic CSS, but I don't know what the elements on the Homepage are named in the app, so I can't address them and customize them. Some examples would be of great help. Thanks.

**Comment by LakorTi** [comment]
It is not recommended to use custom css functions unless there are very special needs. The following is a brief description of some elements:

```
.logo // app logo, also can apply to icon text
.box // favorite item
.title // favorite item icon text
.url // favorite item title, it is confused here :(
.search_bar // search bar
```

**Comment by tuyafeng** [comment]
In the next version(3.9.9), you can directly view the source code of the homepage (android5.0 +), then you can more easily see the relationship between the elements.
