### ISSUE TITLE
In fullscreen mode, menu cut at the top

### ISSUE THREAD

**Issue by issue1001** [LakorTi/Via#436]
In fullscreen mode, long tap menu on a web  page shows up sometimes truncated at the top ( flat instead of rounded corners above 'Open in Background' tab)

![Screenshot_2020-02-17-22-15-15](https://user-images.githubusercontent.com/61279734/74944806-e0650b00-53f6-11ea-9e43-479fb58d36d7.png)

(Happens on Android 7.0 smartphone, res: 1280x720)

**Comment by LakorTi** [comment]
Got it. I will fix it next version(3.9.9).
