### ISSUE TITLE
不能使用prefers-color-scheme接口查询系统是否开启黑暗模式

### ISSUE THREAD

**Issue by RRRRRm** [LakorTi/Via#440]
Via浏览器不支持使用prefers-color-scheme接口查询系统是否开启黑暗模式

prefers-color-scheme接口的使用方法如下
[在web端适配黑暗模式](https://nandovieira.com/supporting-dark-mode-in-web-content)
[prefers-color-scheme接口](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme)

Via浏览器已启用夜间模式, 并打开了夜间模式暗色网页支持. 
在控制台输入`window.matchMedia("(prefers-color-scheme: dark)").matches;` 得到结果为 false, 
而 `window.matchMedia("(prefers-color-scheme: no-preference)").matches;` 得到结果为 true, 
![image](https://user-images.githubusercontent.com/20554448/75456083-0d945900-59b5-11ea-8d20-e0e12ccebfac.png)

换用Chrome测试, `window.matchMedia("(prefers-color-scheme: dark)").matches;` 得到结果为 true.
![image](https://user-images.githubusercontent.com/20554448/75456173-2735a080-59b5-11ea-8ad9-c7d852c870f8.png)

打开一个适配了黑暗模式的网页 [一个例子](https://nandovieira.com/supporting-dark-mode-in-web-content), 发现Via显示的不是作者主动适配的样式. 而Chrome显示正常

Chrome:
![F6E35322803A81474B73BA6328B50583](https://user-images.githubusercontent.com/20554448/75455897-d3c35280-59b4-11ea-9596-fc8530b83555.jpg)

Via:
![18B89462896E80F1E56525D05F0B1126](https://user-images.githubusercontent.com/20554448/75455996-ee95c700-59b4-11ea-9612-1a47b26c153a.jpg)

**Comment by zhfanrui** [comment]
+1

**Comment by LakorTi** [comment]
好，已经跟进了，在 3.9.9 版本中会加上。我这边简单测试了下，直接跟你说结果。

夜间模式的表现：在 3.9.9 版本后，android 10+ 的设备网页会**启用暗色**并且程序网页切换也是暗色，整体浏览体验一致。

关于样式生效的问题：我也很谜，虚拟机测试起来不太方便，测试样式匹配和你测试结果一样，猜测是内核强行注入的脚本？因为即使在未适配样式的网页，依旧强制暗色模式。
