### ISSUE TITLE
"Back" function is broken on this website

### ISSUE THREAD

**Issue by pykko87** [LakorTi/Via#443]
I am using the latest version of Via Browser for Android (3.9.8).

I've spotted a bug on this website: https://forum.softpedia.com/forum/136-soft-related-os/
If you click "Home" button in the left upper corner, it simply reloads current page, it doesn't go to forum's home page.

It happens the same with any sub forum you will visit there.

Can you investigate this ?

**Comment by LakorTi** [comment]
Via will cache several webviews so that your back and forward operations do not need to load the webpage, but this will cause problems with the navigation function of very few webpages. You  can turn off this feature (NOT recommended): "Settings -> Advanced -> Go Back without Reloading".
