### ISSUE TITLE
希望增加让用户自定义UA的数量

### ISSUE THREAD

**Issue by Admin-Account** [LakorTi/Via#444]
不同的场合要用不同的UA 而via不支持安装插件以实现上述功能
所以希望能让用户自行决定新建UA而不是只有一个自定义 而且希望可以让用户命名自定义UA

**Comment by LakorTi** [comment]
自 3.9.8 之后已经支持了「站点设定」，你可以在浏览过程中点击「网址栏左侧放大镜图标」来定义当前站点的部分设置项，其中包括了 UA 设置，我认为这是比增加自定义 UA 数量更优雅的解决方案，因为一旦你为某个站点设定了单独的选项，之后浏览时会自动生效相应的配置，而不是手动切换。
