### ISSUE TITLE
打开时仅载入当前窗口、其他窗口仅记录title标签内容做索引、不要加载。

### ISSUE THREAD

**Issue by kanmurimori** [LakorTi/Via#445]
说一下体验、如果打开的窗口很多退出后你还不想关掉、下次一进来就是好几MB的速度先卡一会儿、有时还卡FC啦。
建议：打开时仅载入当前窗口、**其他窗口**仅记录title标签内容做索引、**不要加载**。
记录title的函数放在打开窗口时执行、下一次起動索引就直接遍历上次的记录、窗口关闭就从数组里删除。

**Comment by LakorTi** [comment]
懒加载标签页这个我很早就想做了，但是因为现在的实现问题，一直没法做，这个之后会完善，但是短期内还完善不了，建议当前还是保持良好的标签习惯。
