### ISSUE TITLE
能否增加针对墨水屏电子书阅读器的一键去除网页背景功能。

### ISSUE THREAD

**Issue by kerncoola** [LakorTi/Via#451]
由于墨水屏只有黑白，如果网页有背景，字体有颜色就会变得很模糊，期待更新。

**Comment by LakorTi** [comment]
或许可以把墨水屏设备的颜色属性设置成灰阶（也称阅读模式），或许会有帮助。如果只是简单的小说或者漫画网站，可以尝试直接关闭 js。因为工作量的原因暂时还不考虑专门针对墨水屏设备的优化，望谅解。
