### ISSUE TITLE
谷歌版比国内版大很多

### ISSUE THREAD

**Issue by jack01-make** [LakorTi/Via#454]
开发者你好，感谢开发。请问国内版和谷歌版有什么区别吗

**Comment by jack01-make** [comment]
谷歌版的反而比较大，有0.9m,国内版只有0.5m，这点我非常疑惑

**Comment by jack01-make** [comment]
同一个版本

**Comment by LakorTi** [comment]
很简单，Google play 的版本支持多语言，而国内版本只有中文、繁中、英文三种语言，同时包名不同。除此之外并无区别。
