### ISSUE TITLE
Unable to save some pages

### ISSUE THREAD

**Issue by AnkushKakne** [LakorTi/Via#48]
Hello this is the best browser available for Android. I only use via browser for browsing. Heartly thanks to the developer for the app but I am having one issue with this browser it does not save some pages in my lenovo k4 note.. I am using the latest version of via browser v3.1.5.  I am providing some links of pages that via browser is not saving.

https://targetstudy.com/iti/trade/27-draughtsman-mechanical/

https://targetstudy.com/iti/trade/69-mechanic-motor-vehicle/

https://targetstudy.com/iti/trade/31-electronics-mechanic/

I am unable to save these and some pages.  Kindly fix the issue.

**Comment by LakorTi** [comment]
Got it. I will fix it in next version(v3.1.8). Please wait for next version.
