### ISSUE TITLE
新版地址栏在底部，编辑不了网址

### ISSUE THREAD

**Issue by funny110** [LakorTi/Via#49]
一点击，输入法就档完了，输网址贼难受，把地址栏放回顶部吧

**Comment by LNDDYL** [comment]
建議 @LakorTi 學習一下Chrome Canary for Android的設計，在一般狀況下address bar在底部，只有在向address bar裡輸入文字時address bar才會移至頂部。

**Comment by LakorTi** [comment]
输入框在安卓4.4的表现会异常，只能是重新设置回传统布局了，在设置-通用-应用布局-传统。
