### ISSUE TITLE
Opening links with image inside opens the image

### ISSUE THREAD

**Issue by ElementFinland** [LakorTi/Via#50]
Hello!

I’m having this slight problem with opening links with images attached to them in the background or in new tab… (so a-tag with an img-tag inside it) the browser seems to always open the image rather than the webpage. Really annoying when the link doesn't have other visible content inside it and it's impossible to open it in a new tab. 

(Also totally besides the point, but about tab says Glean rather than Clean) 

Version: 3.1.5
Android: 7.1.2
Model: Nexus 5X

**Comment by LakorTi** [comment]
OK, the bug had been fixed in latest version. Please update. Thanks for your feedback.
