### ISSUE TITLE
Request page and link-info feature.

### ISSUE THREAD

**Issue by h599** [LakorTi/Via#54]
The feature i want is "page info" (just like what the "uc mini" browser have), the feature that so useful for us the user.

Page info feature mean, we can check what page are we at..

and link-info feature mean, we can check what url are we going to click.

It can make us avoid scamming site, fake login, or even malware site..

After we hold a link for a long time the "dialog" that via browser have, via have an option of "page info" before the "Mark as AD" option.

ScreenShot,
https://ibb.co/fAKyfk
https://ibb.co/iJMN6Q

Please add "page info" and "link-info" feature.. please

**Comment by LakorTi** [comment]
This is a great feature. I will add it. Please wait for next version.
