### ISSUE TITLE
Auto-refresh issue

### ISSUE THREAD

**Issue by h599** [LakorTi/Via#56]
After we switch back to via
via "refresh" all pages we opened
even if the via process still alive, running in background.

It's annoying actually, for example when we are reading an article, we switch to our dictionary app, translate it then switch to via again, via then refresh all the webpages we opened.

**Comment by h599** [comment]
for example: kamus line

**Comment by LakorTi** [comment]
Em...Sorry for this. It look like via had been kill by system. So via reload every lost page. I will try to fix this.
