### ISSUE TITLE
Is there any text selected translation plugin(划词搜索插件)?

### ISSUE THREAD

**Issue by zhangchunlin** [LakorTi/Via#59]
I like Via, if there is this kind of plugin it will be better.
So if there is no this kind of plugin, is there any document to make a plugin for Via?

**Comment by LakorTi** [comment]
Sorry for this. There isn't. The plugin will refactor. I will think about this.

**Comment by zhangchunlin** [comment]
@LakorTi  I install via in a tablet, found that there is a feature to lookup dictionary, but in Phone there is no this feature.
