### ISSUE TITLE
请问 VIA 能否实现屏幕内文字换行？像 OPERA 那样的。

### ISSUE THREAD

**Issue by Mogez** [LakorTi/Via#60]
比如这种，放大后文字如果不重排就得移来移去才看得全，而 Opera 可以动态地重排，实现局部文字屏宽自动换行。
http://www.yhcqw.com/html/psz/2010/913/109131743164C3AA7987138F5IC27838FE2.html

**Comment by LakorTi** [comment]
这个之前有尝试过，但是很失败，效果很不堪所以取消了。后期如果时间充裕会尝试重新整理。

**Comment by Mogez** [comment]
现在 Opera 易主，已经彻底放弃，不过这个黑科技还是值得研究。
