### ISSUE TITLE
Homepage setting

### ISSUE THREAD

**Issue by akinmetin** [LakorTi/Via#89]
User should select what to see in main screen.
For example, I want to see google logo and google search bar with predictions in my open screen(homepage).

**Comment by Ashraf284** [comment]
You can just set your home page to Google.com

**Comment by akinmetin** [comment]
but not like typical url webpage, like unique design for this app.

**Comment by Ashraf284** [comment]
I also vote for that.

**Comment by tuyafeng** [comment]
Just set the search engine to Google then custom homepage (Settings -> Customization).
